apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-poc-deployment
  labels:
    app: node-poc-passive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-poc-passive 
  template:
    metadata:
      labels:
        app: node-poc-passive
    spec:
      containers:
        - name: node-poc-passive
          image: 227295996532.dkr.ecr.ap-northeast-1.amazonaws.com/passive-poc-2285:7  # GitHub Action will replace this
          ports:
            - containerPort: 3001

