name: Cron Demo - Every 1 Minute

on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  cron-test:
    name: Cron Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Print current time
        run: |
          echo "Cron triggered at:"
          date
